f1 = open('../app/math_list.csv', 'r', encoding = 'Big5')
data1 = f1.readlines()
f1.close()
f2 = open('../app/english_list.csv', 'r', encoding = 'Big5')
data2 = f2.readlines()
f2.close()
d1 = {x.split(sep = ',')[0] for x in data1[1:]}
d2 = {x.split(sep = ',')[0] for x in data2[1:]}
ans1 = list(d1.intersection(d2))
ans1.sort()
ans2 = list(d1.union(d2) - d1.intersection(d2))
ans2.sort()
ans3 = list(d1 - d2)
ans3.sort()
ans4 = list(d2 - d1)
ans4.sort()
ans5 = list(d1.union(d2))
ans5.sort()
print(ans1)
print(ans2)
print(ans3)
print(ans4)
print(ans5)
